###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2.0"
services:

    webserver:
      image: nginx:alpine
      container_name: eg-assignment-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    mongodb:
      image: mongo
      container_name: eg-assignment-mongo
      working_dir: /application
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoUser
        - MONGO_INITDB_ROOT_PASSWORD=mongoRootPW
        - MONGO_INITDB_DATABASE=eg_assignment
        - MONGODB_USER=dbuser
        - MONGODB_PASSWORD=dbrootpw
      ports:
        - "27000:27018"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: eg-assignment-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

